### PR TITLE
PermissionGrant: Introduce Support for flashing Gapps

### PR DESCRIPTION
**Pull request by Noeljunior**
* this makes AOSP/CAF based ROMs compatible with 6.0 Gapps packages
* this resolves the problem of permissions not being granted to google core apps
* this will probably need to be updated regulary

* this resolves one aspect of opengapps/opengapps#93

Copyright (C) by Alex Naidis (alex.naidis@linux.com), Team Exodus, The Linux Foundation

Change-Id: Iee4954d0425d8040361ff0fba653c5f1583f3bf2
Signed-off-by: Alex Naidis <alex.naidis@linux.com>

### CODE REVIEW

**Comment by vincent-t** [comment]
This should be merged to fix the gapps problem with following rom: http://forum.xda-developers.com/galaxy-tab-2/galaxy-tab-2-unified/rom-omap4-aosp-project-07-03-t3410092

**Comment by andi34** [comment]
Some gapps (e.g. Gapps from Deltadroid @ XDA) don't need this changes.
On some gapps you need to set the perms before sign in into your Google account, no need to add a workaround here.

**Comment by vincent-t** [comment]
@andi34 This might be true but for OpenGApps this causes some real issues.

**Comment by andi34** [comment]
Why an gapps issue should be our issue?

**Comment by andi34** [comment]
@vincent-t and another big issue are the user:
"(...)If you're planning to install GApps, be sure to read the second post!(...)"
http://forum.xda-developers.com/showpost.php?p=67583029&postcount=2

Imo it includes all needed informations - people only don't read which also is not our fault.

**Comment by vincent-t** [comment]
@andi34 I followed your instructions but I still get the Google Play Services Has Stopped error when set up a google account via settings. I really like your rom and I hope its possible to fix such issues.

**Comment by Ziyann** [comment]
@vincent-t please double-check that you did everything correctly. The procedure has been tested on two different devices with this ROM, and worked every time. Adding the mentioned patch would not only open security holes, but also would require maintenance every time something changes in gapps.

**Comment by andi34** [comment]
Some people face problems because of outdated recovery. Recommend TWRP 3.x for Android 6.
For tab2 you can find it here http://andi34.github.io/recoveries_tab2.html

**Comment by vincent-t** [comment]
@andi34 @Ziyann I use TWRP 3.x. I flashed the rom two times, used different versions of open gapps but the issue still occurs.

**Pull request closed without merging**
